name: Serverless with Python Requirements and deploy options
description: JavaScript action that deploy Serverless  using the serverless-python-requirements plugin using options region and stage

runs:
  using: node20
  # main: src/index.js
  main: index.js

branding:
  icon: arrow-right
  color: red

inputs:
  aws-access-key-id:
    description: AWS Access Key ID. Required if using AWS credentials instead of Serverless Access Key. Serverless V4 requires a serverless access key.
    required: false
    default: ''

  aws-secret-access-key:
    description: AWS Secret Access Key. Required if using AWS credentials instead of Serverless Access Key. Serverless V4 requires a serverless access key.
    required: false
    default: ''

  framework:
    description: The Serverless framework version to install.
    required: false

  serverless-access-key:
    description: Serverless access key. Required if not using AWS credentials. Serverless V4 requires a serverless access key.
    required: false
    default: ''

  working-directory:
    description: The working directory to run Serverless deploy in. Must contain the Serverless config file (e.g. serverless.yaml, serverless.yml).
    required: false
    default: '.'

  region:
    description: The region aws to deploy serverless stack
    required: false
    default: 'us-east-1'
  stage:
    description: The stage of the deploy serverless
    required: false
    default: 'dev'